{% set name = "semi-ate-test-app" %}
{% set version = "1.0.12" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/semi-ate-test-app-{{ version }}.tar.gz
  sha256: 5d282399b4d885687a36637d5ee22063ff87cd84a52fd89463d79f278876c842

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip >=3.8
    - python {{ python_min }}
  run:
    - numpy
    - paho-mqtt
    - pydantic
    - python >={{ python_min }}
    - semi-ate-apps-common
    - semi-ate-common
    - transitions

test:
  imports:
    - ate_test_app
    - ate_test_app.actuators
  commands:
    - pip check
  requires:
    - pip

    - python {{ python_min }}
about:
  home: https://pypi.org/project/semi-ate-test-app/
  summary: Application/Environment that executes a specific test program
  license: GPL-2.0-only
  license_file: ate_test_app/LICENSE.txt

extra:
  recipe-maintainers:
    - nerohmot
