{% set name = "semi-ate-test-app" %}
{% set version = "1.0.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/semi-ate-test-app-{{ version }}.tar.gz
  sha256: 379599707ed37dba3e5413c109a9c5a2344345b91105b6217fff0d49753fb06c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip >=3.8
    - python
  run:
    - numpy
    - paho-mqtt
    - pydantic
    - python >=3.8
    - semi-ate-apps-common
    - semi-ate-common
    - transitions

test:
  imports:
    - ate_test_app
    - ate_test_app.actuators
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/semi-ate-test-app/
  summary: Application/Environment that executes a specific test program
  license: GPL-2.0-only
  license_file: ate_test_app/LICENSE.txt

extra:
  recipe-maintainers:
    - nerohmot
